version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: '--requirepass "123456"'
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
   external: true

