version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - ./keycloak_db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
   external: true
