version: '3'

services:
  dynomite:
    image: dynomitedb/dynomite
    container_name: dynomite
    restart: always
    ports:
      - "8101:8102"
    volumes:
      - ./dynomite.yml:/conf/dynomite.yml
      - ./dynomite.pem:/conf/dynomite.pem
    command: dynomite -c /conf/dynomite.yml

  redis-master1:
    image: redis
    container_name: redis-master1
    ports:
      - "6279:6379"
    command: redis-server --slaveof dynomite 8101

  redis-master2:
    image: redis
    container_name: redis-master2
    ports:
      - "6179:6379"
    command: redis-server --slaveof dynomite 8101
