version: '3.8'
services:
  asynqmon:
    restart: always
    image: hibiken/asynqmon:latest
    ports:
      - "8082:8080"
    environment:
      - REDIS_ADDR=0.0.0.0:6379
      - REDIS_PASSWORD=
    networks:
      - internal

networks:
  internal:
    driver: bridge

