version: '3.8'
services:
  jaeger:
    restart: always
    image: jaegertracing/all-in-one:latest
    container_name: jaegertracing
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5778:5778"
      - "4317:4317"
    networks:
      - backend

networks:
  backend:
   external: true