version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "18880:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

networks:
  backend: