version: '3.8'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3303:3306
    restart: always
    volumes:
      - ./mysql-data5:/var/lib/mysql
      - ./my.cnf5:/etc/mysql/my.cnf
      - ./template.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    networks:
      - backend

networks:
  backend:
   external: true
